pipeline {
    agent any

    environment {
        AWS_REGION = "eu-north-1"
        ECR_REPO   = "447239691587.dkr.ecr.eu-north-1.amazonaws.com/devops-final-app"
        IMAGE_NAME = "devops-final-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-pat',
                    url: 'https://github.com/Giridarun0504/final-devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh '''
                      docker build -t $IMAGE_NAME .
                    '''
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                                  credentialsId: 'aws-credentials']]) {
                    sh '''
                      aws ecr get-login-password --region $AWS_REGION \
                      | docker login --username AWS --password-stdin $ECR_REPO
                    '''
                }
            }
        }

        stage('Tag & Push Image to ECR') {
            steps {
                sh '''
                  docker tag $IMAGE_NAME:latest $ECR_REPO:$IMAGE_TAG
                  docker push $ECR_REPO:$IMAGE_TAG
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Docker image pushed to ECR successfully!"
        }
        failure {
            echo "❌ Pipeline failed. Check logs."
        }
    }
}
